### ISSUE TITLE
How do I use it?

### ISSUE THREAD

**Issue by JeffIrwin** [FernOfSigma/netteikei#1]
Hi!  I have a stupid question because I'm rusty with python, but how do I use this?

I guess I should run something like this:

    python3 netteikei/core.py
    
Is there a `pip` or other package manager setup step that I need to run first?

**Comment by FernOfSigma** [comment]
Apologies for the late response.

As the project is in still its infancy, I haven't gotten to writing proper documentation. I should have done that before asking you to check this out in hindsight.

You can install the project with:
```bash
pip install netteikei[speedups]

# Optional dependencies for the download submodule
pip install netteikei[download]
```

 `core.py` acts as a base for making HTTP calls easier to write in projects that do a bit more than just fetch some data. Its usage is like this (incomplete code, will not run):
```python
import aiohttp
from netteikei import Client, Handler, Request


class MyHandler(Handler):
    async def create_request(self):
        # Read the input data for every call
        ctx = self.ctx.get()
        ...
        return Request.new(url=...) # Whatever you want

    async def process_response(self, res):
        async with res:
            # Do whatever, print or return data

async def my_func():
    # Intended usage
    async with aiohttp.ClientSession() as session:
        my_client = Client(session, MyHandler())
        # Pass `gather` the input data that's read above
        return my_client.gather(...) 
```

An example of this is the [`download.py`](https://github.com/FernOfSigma/netteikei/blob/main/netteikei/contrib/download.py) submodule that does concurrent downloads. Example usage (incomplete code, will not run):
```python
import asyncio
from pathlib import Path

from netteikei.contrib.download import download


my_dir = Path("/you/know/the/rules/")
asyncio.run(download(my_dir, some_url_1, some_url_2))
```

Over time I intend to populate `netteikei.contrib` with utility scripts that I tend to reuse in other projects. That's going to be the main goal of this project.

**Comment by FernOfSigma** [comment]
Marking as closed for now.
